// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceajqyxsmbelpkbmdzkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlYWpxeXhzbWJlbHBrYm1kemt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5OTYxMzYsImV4cCI6MjA0ODU3MjEzNn0.7y42gKReYcjHjbK74I6wjLqF_Co573acuTQp9Ntd_PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);